/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Get all fonts that can render SC (Simplified Chinese) characters, note that this will attempt to load all fonts
 * to determine whether it matches the requirements or not.
 */
export declare function getScFonts(): Promise<string[]>

/** Get all font families available on the system. */
export declare function getSystemFonts(): string[]
