
[package]
authors = ["YUCLing <luotianyi@luotianyi.me>"]
edition = "2021"
name    = "smtc"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi.workspace = true
napi-derive.workspace = true

[target.'cfg(windows)'.dependencies.windows]
version = "0.62"
features = [
    "Media",
    "Media_Playback",
    "Foundation",
    "Storage_Streams"
]

[build-dependencies]
napi-build = "2"
