/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MediaSession {
  constructor()
  setEventHandler(handler?: (((err: Error | null, arg: MediaSessionEvents) => void)) | undefined | null): void
  setMetadata(metadata?: SmtcMetadata | undefined | null): void
  setPlaybackStatus(status: string): void
  setPlaybackRate(rate: number): void
  /** Update the SMTC timeline. Both values are in 100 ns ticks. */
  setTimelineProperties(position: number, duration: number): void
}

export type MediaSessionEvents =
  | { type: 'Play' }
  | { type: 'Pause' }
  | { type: 'Next' }
  | { type: 'Previous' }
  | { type: 'Stop' }
  | { type: 'SetPosition', position: number }
  | { type: 'SetRate', rate: number }

export interface SmtcMetadata {
  title?: string
  artist?: string
  album?: string
  albumArtist?: string
  artUrl?: string
}
