/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MediaSession {
  constructor()
  setEventHandler(handler?: (((err: Error | null, arg: MediaSessionEvents) => void)) | undefined | null): void
  /** Replaces the whole Now Playing info dictionary. `None` clears it. */
  setMetadata(metadata?: NowPlayingMetadata | undefined | null): void
  /** macOS-specific playback state (used on macOS for Now Playing visibility). */
  setPlaybackState(state: string): void
}

export type MediaSessionEvents =
  | { type: 'Play' }
  | { type: 'Pause' }
  | { type: 'Toggle' }
  | { type: 'Next' }
  | { type: 'Previous' }
  | { type: 'SetPosition', position: number }
  | { type: 'SetRate', rate: number }

export interface NowPlayingMetadata {
  title?: string
  artist?: string
  album?: string
  duration?: number
  elapsed?: number
  rate?: number
  /** Album-art URL string (or empty for none). */
  artUrl?: string
}
