/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  constructor(path: string)
  /** Execute a single SQL statement with named parameters. */
  execNamed(sql: string, parameters: Record<string, unknown>): Promise<[number, Record<string, unknown>[]]>
  /** Execute a single SQL statement with positional (`?`) parameters. */
  exec(sql: string, parameters: unknown[]): Promise<[number, Record<string, unknown>[]]>
  /**
   * Execute SQL string, returns an array of objects representing rows,
   * and an array of performance info (total time, execution time, rows affected).
   *
   * For NCM, not intended for Open Orpheus.
   */
  executeSql(sql: string): Promise<[number, Record<string, string>[], [number, number, number]]>
  /**
   * Execute a SQL contains multiple statements as one transaction.
   *
   * For NCM, not intended for Open Orpheus.
   */
  executeTransaction(sql: string): Promise<[number, Record<string, string>[], [number, number, number]]>
  /**
   *  Execute multiple SQL statements inside an array, returns values of the last statement as an array.
   *
   *  ## Example return
   *  ```json
   *  {
   *     "value": [
   *         [
   *             "a",
   *             "b"
   *         ]
   * }
   *  ```
   *
   *  For NCM, not intended for Open Orpheus.
   */
  executeSqls(sqls: string[]): Promise<{ value: string[][] }>
}
