/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Decodes AV3A and renders it to interleaved 16-bit stereo.
 *
 * See `render.rs` for the render itself.
 */
export declare class Av3aRenderSession {
  constructor()
  /**
   * Decode and render the AV3A frames in `input`.
   *
   * Returns interleaved stereo int16, one output frame per input frame.
   */
  decode(input: Buffer, sampleSizes?: number[] | undefined): Promise<Buffer>
  /** Drop decoder overlap and limiter state, for a discontinuous jump. */
  reset(): void
  close(): void
}

export interface Av3aMp4Index {
  samples: Array<Av3aMp4Sample>
  sampleRate: number
  samplesPerFrame: number
  /**
   * Frames the caller must decode ahead of a seek target to refill the
   * decoder's synthesis overlap.
   */
  warmupFrames: number
}

/** One access unit: a single AV3A frame in `mdat`. */
export interface Av3aMp4Sample {
  offset: number
  size: number
}

/**
 * Build the full AV3A index from a complete `moov` box and its first sample.
 *
 * The two buffers are intentionally independent: for a non-fast-start MP4,
 * `moov` can be fetched from the tail while the first sample is fetched from
 * the beginning, without materialising the intervening media bytes.
 */
export declare function indexAv3aMp4Moov(moov: Buffer, firstSample: Buffer): Av3aMp4Index

/** Read only the first sample's location from a complete `moov` box. */
export declare function readAv3aMp4FirstSample(moov: Buffer): Av3aMp4Sample
